# Generated by Django 4.0.2 on 2022-03-01 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created'], 'verbose_name_plural': 'Profiles'},
        ),
    ]
