# Generated by Django 4.0.1 on 2022-01-21 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_featured_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='featured_image',
            new_name='featured_images',
        ),
    ]
