# Generated by Django 4.0.1 on 2022-01-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_featured_image_project_featured_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_images',
            field=models.ImageField(blank=True, default="{% static 'images/default.jpg' %}", null=True, upload_to=''),
        ),
    ]
