# Generated by Django 4.0.1 on 2022-01-21 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_featured_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='featured_images',
        ),
    ]
