# Generated by Django 4.0.1 on 2022-01-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_project_featured_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='../static/images/default.jpg', null=True, upload_to=''),
        ),
    ]
