# Generated by Django 4.0.1 on 2022-01-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video_demo',
            field=models.FileField(blank=True, null=True, upload_to='demo/'),
        ),
    ]
