# Generated by Django 4.0.1 on 2022-01-28 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_video_demo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='video_demo',
        ),
    ]
