# Generated by Django 4.0.2 on 2022-02-11 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_project_options_review_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_ratio', '-vote_total', 'title'], 'verbose_name_plural': 'Projects'},
        ),
    ]
